LICENSE
README.md

This pull request adds licensing information for the repository's contents. If a license header is not included in files, they are assumed to fall under the [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/) or the [Creative Commons Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/), depending on what type of content it is (e.g. code vs. a guide).
I am doing it in this way to allow flexibility for a future contributor to choose their own OSI-approved license in the event they do not like the MPL or CC-BY-SA.

Add assumed licenses (MPL or CC-BY-SA 4.0) for content in the repo

---

scripts/xo-eol-repos/f18/fedora-updates.repo
scripts/xo-eol-repos/f18/fedora.repo
scripts/xo-eol-repos/f18/fix_repos.sh

This pull request attempts to fix issue #3.
The script pulls down the GPG public keys used for Fedora 18 package signing. It imports those keys into the system. Afterwards, it pulls down the repo files that have the correct `baseurl`, deletes the old files, and replaces them with the new.
After doing this, the XO user should be able to use `yum` once again.
This will allow students to interact with `yum` in the command line on the XO to install software. At the beginning of my HFOSS course, my XO laptop was a freshly flashed system. Because of this, the repo files in the system were made to point to the URLs used if Fedora 18 were still a supported release. However, that is not the case. F18 hit EoL status many years ago. This script just adjusts the system to use the accurate GPG keys …

Create script to fix EoL repos on XO laptops (fixes #3)

---

Vagrantfile
roles/mariadb/templates/my.cnf.j2
roles/nginx/tasks/main.yml
roles/nginx/templates/fossrit.jwf.io.conf
roles/nginx/templates/restrictions.conf
roles/nginx/templates/wordpress.conf
roles/php-fpm/templates/wordpress.conf

_Optionally tagging @nlMeminger, @ct-martin, and @ritjoe for review._
---
This commit brings all existing roles together and integrates them. It
makes it possible for someone to use these roles in conjunction with
each other, such as for a server configuration. It allows us to move
forward with running it on our infrastructure.
A summation of changes:
MariaDB
-------
* Copy defaults from current MariaDB configuration
php-fpm
-------
* Minor syntax cleanup
nginx
-----
* Split configurations out into three different globs
* **restrictions.conf**: Base set of restrictions for all sites
* **wordpress.conf**: Base set of guidelines for any WordPress site
* **fossrit.jwf.io**: Single installed WordPress site
* Adjust various settings with PHP
Ansible
-------
* Update nginx role task to load in …

Integrate all roles together for full deployment

---

roles/matterbridge/templates/matterbridge.toml

Closes FOSSRIT/infrastructure#28.

[matterbridge] hide protocol prefix (i.e. [slack]) in IRC

---

playbooks/apps/matterbridge.yml

This pull request adds a playbook for the `matterbridge` role. It shortens run time for playbook re-runs. It's intended for pushing minor changes instead of running an entire host's playbook.

[matterbridge] add app-specific playbook for faster runs after changes

---

docs/discourse.adoc

Closes FOSSRIT/tasks#90.
This commit adds a new document written in AsciiDoc to explain how the
Discourse website infrastructure is deployed. This intends to create a
trail of how the application is deployed and how changes can be made
(and who to contact) in the future.
This needs more expansion, like how DNS is handled for the
fossrit.community domain, but this is a start for now.
---
_Edit_: A rendered version of this document lives [here](https://github.com/FOSSRIT/infrastructure/blob/8d85ca4a1ad1a2b5779d6a915dcf4de9de94227e/docs/discourse.adoc).

docs: Document how fossrit.community Discourse website is deployed

---

roles/matterbridge/tasks/main.yml
roles/matterbridge/vars/main.yml

This commit changes the following:
* Updates Matterbridge to latest upstream version, v1.15.0
* Changes distribution method to follow latest format by upstream
The v1.15.0 upgrade includes a bugfix from v1.14.2 that affected the IRC
bridge. In previous versions, the bot would not reconnect automatically
or gracefully if it lost connection to the IRC server. Now, the bot
should automatically reconnect if the connection is terminated or broken
for some reason. cc: @Tjzabel @ct-martin
Additionally, upstream also ships releases in a new format. I changed
the URL schema to match the new format and changed the checksums to
sha256sum since upstream provides those in a release. Previously, I was
calculating sha512sums manually, which isn't exactly straightforward.
---
This change was tested and …

matterbridge: Update to v1.15.0, update distribution URLs

---

roles/matterbridge/vars/main.yml

No breaking changes I see that should affect us, but another set of eyes
are always welcome:
https://github.com/42wim/matterbridge/releases/tag/v1.15.1
Signed-off-by: Justin W. Flory <git@jwf.io>

matterbridge: Upgrade to latest v1.15.1 upstream

---

roles/jwflory.teleirc/vars/main.yml

This is a super simple PR, but may have implications.
This PR makes the `#rit-foss` IRC channel use TeleIRC's latest HEAD. In order to get a better feel of how TeleIRC is working before a release, I would like to make use of `#rit-foss`'s extra user traffic in order to pin down issues sooner.

Make #rit-foss use HEAD for TeleIRC.

---

roles/jwflory.teleirc/vars/main.yml

Brings us to the latest upstream release. Fixes HTML rendering in messages.

teleirc: Version bump to v1.3.2

---

roles/matterbridge/vars/main.yml

This brings us to the latest upstream version of matterbridge. Nothing
new in this release for the IRC or Slack bridges, but it does update
some dependencies.
I haven't ran this yet. I'll run the playbook after it merges to `master`.

matterbridge: Upgrade to latest upstream, v1.16.0

---

roles/matterbridge/vars/main.yml

I forgot this step previously. Since the last PR passed review, I made these changes locally and ran the playbook. Everything checked out.

matterbridge: Update release sha256sum hash from upstream

---

roles/matterbridge/vars/main.yml

Includes a newer emoji library and a minor Slack bugfix:
https://github.com/42wim/matterbridge/releases/tag/v1.16.2

matterbridge: v1.16.1 -> v1.16.2

---

docs/upgrade-matterbridge.adoc

I haven't documented what this process is and it is an essential part of
RIT FOSS infrastructure. This attempts to explain the upgrade process
for Matterbridge as I have been doing it for the last year.

docs: Add explainer on how to upgrade Matterbridge

---

inventory/inventory
playbooks/metrics.yml
roles/base/ubuntu-18.04-lts/tasks/main.yml

This commit adds the College of Art and Design virtual machine in
Institute Hall to the Ansible inventory. Along with it, I added a new
base role for an Ubuntu 18.04 LTS machine, since this is the operating
system that the CAD admins use as a base. Additionally, I also added a
new playbook to run the role on the host. I tested this locally before
committing and verified it all works.
Currently, I'm hard-coding my RIT computer account as the login user,
which obviously is a hard block on me. A future next step is to set up
an Ansible system user for running playbooks. I need to think about this
harder before implementing, but in the meanwhile, this commit gets us
rolling.
cc: @Nolski @Tjzabel

Add metrics host to inventory

---

roles/matterbridge/templates/matterbridge.toml
roles/matterbridge/vars/main.yml

This commit changes the Matterbridge role to add a new bridge to the
`#python` Slack channel and the `#rit-python` IRC channel.

matterbridge: Join #rit-python + #python

---

roles/jwflory.teleirc/vars/main.yml

This brings our deployed version of TeleIRC to the latest supported
upstream release.

teleirc: Upgrade v1.3.2 -> v1.3.3

---

roles/matterbridge/vars/main.yml

This bumps us to the newest release of Matterbridge, v1.16.3, released
by @42wim. Most notably, this includes a bug fix for the Slack bridge
and rate-limiting, something we noticed on our side at some point in the
last month.
https://github.com/42wim/matterbridge/pull/959
CC: @thenaterhood @Tjzabel @Nolski… anyone else that noticed this…

matterbridge: Upgrade v1.16.2 -> v1.16.3

---

roles/matterbridge/templates/matterbridge.toml
roles/matterbridge/vars/main.yml

This commit reorganizes the channels used for the `#ritlug`/`#general`
channel and the `#ritlug-teleirc`/`#teleirc` channels. This change is
done because RIT/FOSS@MAGIC is registered to the `#rit-*` namespace. Any
channels that fall underneath the umbrella of the `#rit-*` namespace
enable Freenode operators to provide support to organization admins to
troubleshoot or change permissions in channels. This also allows us to
follow a better categorization system for channels, e.g. FOSS@MAGIC
admins control `#rit-*` channels, but RITlug eboard controls
`#rit-lug-*` channels. Just an example!
The commit does exactly the following:
1. Renames vars file channels to use RIT namespace format
2. Adds temporary manual entry in matterbridge config to route traffic
into `#ritlug` and `#ritlug-teleirc`, …

matterbridge: Unify IRC channels to RIT namespace

---

playbooks/manual/purge_teleirc_ritlug_bots.yml
roles/jwflory.teleirc/vars/main.yml

Recently, the `#ritlug*` IRC channels were moved to the `#rit-lug*`
namespace. This was done to bring the channels under the Freenode
project registration we have for the `#rit-*` channels. This grants us
more control over what happens in these channels, as they are tied to
our Freenode project registration.

teleirc: Adjust IRC channel names (#ritlug* -> #rit-lug*)

---

roles/matterbridge/templates/matterbridge.toml
roles/matterbridge/vars/main.yml

This commit retires the deprecated channels by removing the Matterbridge
bot from the old channels. Last week, we successfully migrated the IRC
channels to the RIT-registered namespace on Freenode. The two-way bridge
across two channels will be removed once the playbook runs with this
commit included.
Also, the diff is hard to read because I reorganized the channels
alphabetically to make it easier to maintain this file if it grows over
time. Sorry.

matterbridge: Deprecate #ritlug/#ritlug-teleirc IRC channels

---

.github/CODEOWNERS

This commit adds a CODEOWNERS file. It works similar to a `gitignore`,
except it integrates with the GitHub PR review functionality. In this
case, the @FOSSRIT/ansible-maintainers team will always get pinged for
reviews on new pull requests in this repo.

Add CODEOWNERS file for automatic review requests

---

roles/matterbridge/vars/main.yml

This brings our Matterbridge instance up to the latest upstream version.
No major bug fixes or features relevant for our use case, but bringing
us up-to-date because, might as well.
At commit time, this change is already deployed in production.

matterbridge: Upgrade to v1.16.5

---

roles/matterbridge/vars/main.yml

Matterbridge upstream released a new minor feature release:
https://github.com/42wim/matterbridge/releases/tag/v1.17.0
There are a good number of changes, including support for Microsoft
Teams. (What?!) But the relevant bits of the changelog for us are below:
* general: support JSON and YAML config formats (42wim/matterbridge#1045)
* irc: Be less lossy when throttling IRC messages (42wim/matterbridge#1004)
* slack: Use upstream slack-go/slack again (42wim/matterbridge#1018)
* slack: Ignore ConnectingEvent (42wim/matterbridge#1041)
* slack: use blocks not attachments (42wim/matterbridge#1048)
* slack: Fix 42wim/matterbridge#1039: messages sent to Slack being synced back (42wim/matterbridge#1046)
And a hat tip to our upstream devs who made this release possible:
@qaisjp, @jakubgs, …

matterbridge: Upgrade to v1.17.0 release

---

.travis.yml

Pretty sure I forgot to delete this line when I copied the Travis config
from another one of my repos. Doesn't make sense to have
FOSSRIT/infrastructure notifications echo in my IRC support channel.

ci: Stop alerting in `##jwf` on Freenode IRC

---

roles/matterbridge/vars/main.yml

New minor release of Matterbridge upstream. None of the changes impact
our usage, but I prefer to remain current on upgrades to avoid to many
changes piling on all at once:
https://github.com/42wim/matterbridge/releases/tag/v1.17.1
At commit time, this change was already run and pushed to production.

matterbridge: Upgrade to v1.17.1

---

roles/matterbridge/vars/main.yml

Periodic version bump. A few upstream changes highlighted that may be
relevant for us:
https://github.com/42wim/matterbridge/releases/tag/v1.17.3
v1.17.3
=======
* irc: Add JoinDelay option (irc). Fixes 42wim/matterbridge#1084
(42wim/matterbridge#1098)
* slack: Clip too long messages on 3000 length (slack). Fixes
* This one will definitely affect RIT FOSS for IRC/Matrix/Riot users
with really long messages to Slack.
42wim/matterbridge#1081 (42wim/matterbridge#1102)
* slack: Prevent image/message looping (slack). Fixes
42wim/matterbridge#1088 (42wim/matterbridge#1096)
* irc: Add extra space before colon in attachments (irc). Fixes
42wim/matterbridge#1089 (42wim/matterbridge#1101)
v1.17.2
=======
* slack: Update vendor slack-go/slack (42wim/matterbridge#1068)

matterbridge: v1.17.1 -> v1.17.3
